PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Consulta.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLaMejor.App.Persistencia;
using PizzaLaMejor.App.Dominio;

namespace PizzaLaMejor.App.Presentacion.Pages
{
    public class ConsultaModel : PageModel
    {
        private readonly IRepositorioClientes _repoCliente;
        [BindProperty]
        public IEnumerable<Cliente> ListaCliente{get;set;}
        public ConsultaModel(IRepositorioClientes repoCliente)
        {
            _repoCliente = repoCliente;
        }
        public void OnGet(int clienteId)
        {
            ListaCliente = new List<Cliente>(); 
            ListaCliente = _repoCliente.ConsultarCliente();
            _repoCliente.EliminarCliente(clienteId); 
        }
    }
}

PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Edicion.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLaMejor.App.Persistencia;
using PizzaLaMejor.App.Dominio;

namespace PizzaLaMejor.App.Presentacion.Pages
{
    public class EdicionModel : PageModel
    {
        private readonly IRepositorioClientes _repoCliente;
        [BindProperty]
        public Cliente cliente{get;set;}
        public EdicionModel(IRepositorioClientes repoCliente)
        {
            _repoCliente = repoCliente;
        }
        public void OnGet(int clienteId)
        {
            cliente= _repoCliente.ConsultarCliente(clienteId);
        }
        public async Task<IActionResult> OnPost()
        {
            cliente = _repoCliente.ActualizarCliente(cliente);
            if(cliente==null){
                return Page();
            }
            return RedirectToPage("/Clientes/Consulta");
        }
    }
}
 

PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Edicion2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLaMejor.App.Dominio;
using PizzaLaMejor.App.Persistencia;


namespace PizzaLaMejor.App.Presentacion.Pages
{
    public class Edicion2Model : PageModel
    {
        
        private readonly IRepositorioClientes _repoCliente;
        [BindProperty]
        public Cliente cliente{get;set;}  
        public Edicion2Model(IRepositorioClientes repoCliente)
        {
            _repoCliente = repoCliente;
        }
        public void OnGet()
        {
            cliente = new Cliente();
        }

        public async Task<IActionResult> OnPost()
        {
            cliente = _repoCliente.ConsultarClientePorCorreo(cliente.CorreoElectronico);
            if(cliente==null)
            {
                return RedirectToPage("/Error");
            } 
            else
            {
                return Page();
            }
            
        }
        public async Task<ActionResult> OnPostEdit()
        {
            cliente = _repoCliente.ActualizarCliente(cliente);
            if(cliente!=null)
            {
                return RedirectToPage("/Clientes/Consulta");
            }
            return RedirectToPage("/Error");
        }
    }
}

PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Registro.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLaMejor.App.Dominio;
using PizzaLaMejor.App.Persistencia;


namespace PizzaLaMejor.App.Presentacion.Pages
{
    public class RegistroModel : PageModel
    {   
        private readonly IRepositorioClientes _repoCliente;

        public RegistroModel (IRepositorioClientes repoCliente)
        {
            _repoCliente = repoCliente;
        }

        [BindProperty]
        public Cliente cliente {get; set;}
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if(!ModelState.IsValid){
                return Page();
            }
            _repoCliente.CrearCliente(cliente);
            return RedirectToPage("/Index");
        }
    }
}

PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Consulta.cshtml
@page
@model PizzaLaMejor.App.Presentacion.Pages.ConsultaModel
@{
}


<h2 class="text-warning">Lista Clientes</h2>

    <style>
        body {
            background-color: rgb(235, 237, 239);
        }
    </style>



<table class="table">
    <tr>
        
        <td>Cedula</td>
        <td>Nombres</td>
        <td>Apellidos</td>
        <td>CorreoElectronico</td>
        <td>Telefono</td>
        <td>Direccion</td>
        
        

    </tr>
    
        @foreach(var x in Model.ListaCliente){
        <tr>    
            
            <td>@x.Cedula</td>
            <td>@x.Nombres</td>
            <td>@x.Apellidos</td>
            <td>@x.CorreoElectronico</td>
            <td>@x.Telefono</td>
            <td>@x.Direccion</td>
           
            <td>
                <a asp-page="/Clientes/Edicion" class="btn btn-secondary" asp-route-clienteId=@x.Id>Editar</a>
            </td>
            <td>
                <a asp-page="/Clientes/Consulta" class="btn btn-dark" asp-route-clienteId=@x.Id>Eliminar</a>
            </td>
        </tr>    
        }
    
</table>
        <br> 
        <div class="input-group mb-3">
            
            <a class="btn btn-warning" asp-page="/Clientes/Registro" style="display: block; margin: 0 auto;">Registrar Nuevo Cliente</a>
                        
            <a class="btn btn-warning" asp-page="/Clientes/Edicion2" style="display: block; margin: 0 auto;">Buscar Cliente</a>
        </div>




        

PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Edicion.cshtml
@page
@model PizzaLaMejor.App.Presentacion.Pages.EdicionModel
@{
}

<h2 class="text-warning">Editar datos del Cliente</h2>

    <style>
        body {
            background-color: rgb(235, 237, 239);
        }
    </style>

<br>


<div class="border" style="background-color: #BFC9CA;">
    <form method="post">

        <input type="hidden" asp-for="cliente.Id">
        <div class="input-group mb-3">

            <input type="text" asp-for="cliente.Nombres" class="form-control" placeholder="Nombres">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Apellidos" class="form-control" placeholder="Apellidos">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Cedula" class="form-control" placeholder="Cedula">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.FechaNacimiento" class="form-control" placeholder="FechaNacimiento">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Telefono" class="form-control" placeholder="Telefono">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Direccion" class="form-control" placeholder="Direccion">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.CorreoElectronico" class="form-control" placeholder="CorreoElectronico">
        </div>

        <div class="input-group mb-3">
            <input type="submit" value="Guardar" class="btn btn dark form-control">
        </div>


    </form>

</div>

PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Edicion2.cshtml
@page
@model PizzaLaMejor.App.Presentacion.Pages.Edicion2Model
@{
}


<h2 class="text-warning">Consultar Cliente</h2>

    <style>
        body {
            background-color: rgb(234, 237, 237);
        }
    </style>

<div class="border">
    <form method="post">
        <label for="">Correo Electronico</label>
        <input asp-for="cliente.CorreoElectronico">
        <input type="submit" value="Consultar" class="btn btn-warning form-control">
    </form>

</div>
 
 <br>


<div class="border" style="background-color: #BFC9CA;">
    <form method="post" asp-page-handler="edit">

        <input type="hidden" asp-for="cliente.Id">
        <div class="input-group mb-3">

            <input type="text" asp-for="cliente.Nombres" class="form-control" placeholder="Nombres">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Apellidos" class="form-control" placeholder="Apellidos">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Cedula" class="form-control" placeholder="Cedula">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Telefono" class="form-control" placeholder="Telefono">
        </div>

        <div class="input-group mb-3">
            <input type="text" asp-for="cliente.Direccion" class="form-control" placeholder="Direccion">
        </div>

        
        <div class="input-group mb-3">
            <input type="submit" value="Guardar" class="btn btn dark form-control">
        </div>


    </form>

</div>

PizzaLaMejor.App/PizzaLaMejor.App.Presentacion/Pages/Clientes/Registro.cshtml
@page
@model PizzaLaMejor.App.Presentacion.Pages.RegistroModel
@{
}

<br>

<h2 class="text-warning">Crear Cliente</h2>
    <style>
        body {
            background-color: rgb(234, 237, 237);
        }
    </style>

<div class="border">
    <form method="post">
        <div class="container" style="padding: 30px">

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="cliente.Nombres"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="cliente.Nombres" class="form-control">
                    </div>
                    <span asp-validacion-for="cliente.Nombres" class="tex-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="cliente.Apellidos"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="cliente.Apellidos" class="form-control">
                    </div>
                    <span asp-validacion-for="cliente.Apellidos" class="tex-danger"></span>
                </div>
            </div>
        
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="cliente.Cedula"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="cliente.Cedula" class="form-control">
                    </div>
                    <span asp-validacion-for="cliente.Cedula" class="tex-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="cliente.FechaNacimiento"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="cliente.FechaNacimiento" class="form-control">
                    </div>
                    <span asp-validacion-for="cliente.FechaNacimiento" class="tex-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="cliente.Telefono"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="cliente.Telefono" class="form-control">
                    </div>
                    <span asp-validacion-for="cliente.Telefono" class="tex-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="cliente.Direccion"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="cliente.Direccion" class="form-control">
                    </div>
                    <span asp-validacion-for="cliente.Direccion" class="tex-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="cliente.CorreoElectronico"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="cliente.CorreoElectronico" class="form-control">
                    </div>
                    <span asp-validacion-for="cliente.CorreoElectronico" class="tex-danger"></span>
                </div>
            </div>

        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <input type="submit" value="Crear" class="btn btn-warning form-control">
                </div>
                <div class="col-sm-4">
                    <a asp-page="/Index" class="btn btn-dark form-control">Volver</a>
                </div>
            </div>
        </div>
</div>


</form>
</div>